### ISSUE TITLE
About reproducing the proto net results with ConvNet

### ISSUE THREAD

**Issue by flexibility2** [Sha-Lab/FEAT#13]
@Han-Jia , Thanks for your source code! But I have some troubles in reproducing them.
I have achieved only **51.97%** for the 1-shot 5-way of ConvNet case and **70.60%** for 5-shot 5-way of ConvNet case.  The hyper-parameters I used is:

- --lr 0.0001 --temperature 32 --max_epoch 200  step_size (schedulr) = 10, gamma=0.2 for 1-shot 5-way of ConvNet

- --lr 0.0001 --temperature 32 --max_epoch 200  step_size (schedulr) = 10, gamma=0.2 for 5-shot 5-way of ConvNet

Should I make any changes to other default parameters to reproduce the result in Table1 (**52.61%** and **71.33%** test acc)?

any information will be greatly appreciated

**Comment by Han-Jia** [comment]
Hello, 

For the ConvNet backbone, please try

- --lr 0.0001 --temperature 64 --max_epoch 200 step_size (schedulr) = 50, gamma=0.1 for 1-shot 5-way of ConvNet

- --lr 0.0001 --temperature 16 --max_epoch 200 step_size (schedulr) = 30, gamma=0.1 for 5-shot 5-way of ConvNet

1. For the temperature, it seems high-temperature value will not degrade the results. It's better to try larger temperature values.
2. You can also increase the number of validation tasks to select the best model.
