### ISSUE TITLE
Intitialisation vs final weights

### ISSUE THREAD

**Issue by willwilliams** [Sha-Lab/FEAT#14]
I think your provided weights for the initialisation are mixed with your final weights.

The README states:
1) Pre-trained weights are here - https://drive.google.com/open?id=14Jn1t9JxH-CxjfWy4JmVpCxkC9cDqqfE
2) The learned models are here - https://drive.google.com/open?id=1ZjkiEJh_96VYNWCOXUGsPuesLaFzV_z9

For MiniIMageNet-Res-5-Shot-5-Way.pth at the very least these appear to be the wrong way round.

Can you confirm?

**Comment by willwilliams** [comment]
Also, it appears the weights provided don't include those for the transformer. Is this expected?

**Comment by Han-Jia** [comment]
Hi,

To evaluate the model with the final weights, please also set the parameters like "shot" and "model" in the script. For the MiniImageNet with 5-shot 5-way, it is expected to get accuracy around 78%.

For the initialization weight, it only contains the parameters of the backbone. So the pre-trained weight only relies on the backbone but not the full model. It can also be used for MatchNet and ProtoNet.

**Comment by d12306** [comment]
Hi, @Han-Jia ,First thank for your implementation . So this code implements the feat, not the feat*, right? Could you please upload the code for feat* cause I am little confused with this setting, is it basically mean the input into the transformer are the (shot + query) meta-train images and some of the meta-test images?
