### ISSUE TITLE
Performance of instance embeddings without training

### ISSUE THREAD

**Issue by mctigger** [Sha-Lab/FEAT#16]
Hi,
can you tell me what the performance of the pretrained backbones is if their embeddings are not further adapted or trained in a few-shot setting, but only evaluated?

Best regards,
Tim

**Comment by Han-Jia** [comment]
Hi, Tim, 

For ConvNet, the pretrained embedding gets 1-shot performance near 46% (based on distance measure). For ResNet, it gets about 55%.

You can directly use eval_matchnet/protonet with the pretrained embedding to get the precise few-shot classification performance for the pretrained embedding.

**Comment by mctigger** [comment]
Thanks a lot!
