### ISSUE TITLE
Evaluation not working

### ISSUE THREAD

**Issue by mctigger** [Sha-Lab/FEAT#18]
It seems like `eval_feat.py` doesn't work currently.

Also I am not able to reproduce evaluation results for feat* with the pretrained models. Can you check whether this currently works?

**Comment by Han-Jia** [comment]
Hi, I have fixed eval_feat.py. (The provided pre-trained model weigths are for the FEAT*)

**Comment by mctigger** [comment]
Thank you very much. 
Can you if possible check whether https://github.com/yaoyao-liu/mini-imagenet-tools uses the same miniimagenet data as you do? (scroll to the bottom for a download link). I tried reproducing the results with yaoyao's dataset, but so far I get lower scores.

Or could you possibly send me the miniimagenet data, so I can check myself? 

I am very grateful for your help!

**Comment by Han-Jia** [comment]
Hello,
The images in the provided link are preprocessed in advance. I run the experiments on the original images. You can send emails to [Sachin Ravi](https://github.com/twitter/meta-learning-lstm) for the link of the original dataset.

**Comment by mctigger** [comment]
Are the original dataset equal to this one? https://github.com/renmengye/few-shot-ssl-public
I get around 60% acc only...

**Comment by XJay18** [comment]
@Han-Jia  Could you post a link of the original dataset since you have run the experiments on that? I also fail to reproduce the results in the paper. 
Many thanks!

**Comment by Han-Jia** [comment]
@mctigger sorry for the late reply. This data set is still the one pre-processed to 84x84 in advance. 

@XJay18 I asked Sachin Ravi for the link of the data set (it contains original images). I'm not sure whether I can release the link directly. Please send emails to him (sachinr@princeton.edu) for the download link).
