### ISSUE TITLE
About reproducing result on CUB dataset

### ISSUE THREAD

**Issue by daiszh** [Sha-Lab/FEAT#22]
I tried to evaluate the feat on CUB dataset using your provided checkpoint: 

`
python eval_feat.py --model_type ConvNet --dataset CUB --model_path ./saves/FEAT-Models/CUB-Conv-1-Shot-5-Way.pth --shot 1 --way 5 --gpu 0
`

But only get Test Acc 0.5310 + 0.0022. Is there anything need to be modified to reproduce the result in the paper (68.87%)?

**Comment by Han-Jia** [comment]
Hi, daiszh,

Sorry for the late reply. I re-run the command on my machine, and it could get similar results as re-produced in the paper.
1. The saved models are for FEAT_STAR, you can also try eval_feat_star with the model. (I find the weights for feat_star can also apply for FEAT)
2. I crop the CUB images based on the bounding box as usual. Do you use the original images?
3. Maybe you can try re-train the model.
