### ISSUE TITLE
1 shot & 5 shot training

### ISSUE THREAD

**Issue by Franklin-Yao** [Sha-Lab/FEAT#25]
Do you train 1 shot and 5 shot separately? Some papers use large numbers of shots, such as 15 to train a model once and test for 1 shot and 5 shot. [MetaOptNet](https://github.com/kjunelee/MetaOptNet) is the case.

**Comment by Han-Jia** [comment]
Hi, Franklin-Yao,

The 1-shot and 5-shot models are trained separately.
