### ISSUE TITLE
Download links for trained models

### ISSUE THREAD

**Issue by pratikm141** [Sha-Lab/FEAT#26]
Hi, can you please provide download links to the trained models for tiered imagenet.

**Comment by Han-Jia** [comment]
Hi, please download the learned model from this [link](https://drive.google.com/drive/folders/1L15ddQJysiZEVTEMYy7do2_XblGIViyy?usp=sharing). We will update the link on the main page soon.

**Comment by pratikm141** [comment]
Thanks :)
Can you also provide the links for the other datasets trained models

**Comment by Han-Jia** [comment]
MiniImageNet: 
[ConvNet](https://drive.google.com/drive/folders/1ZbTaFUqgE8i-mEELDLJXf7rgXjQACaEX?usp=sharing);
[ResNet](https://drive.google.com/drive/folders/1PgjybQHxjP65MvcI4C1vnMCPsvsoaAFJ?usp=sharing)

**Comment by pratikm141** [comment]
Thanks :)

**Comment by hgoyal5** [comment]
@Han-Jia are the CUB trained models available?

**Comment by Han-Jia** [comment]
Please download the trained model on CUB with ConvNet at [here](https://drive.google.com/open?id=1E8yNjOmnwD7IebawY1Hle2CoUOgKrxFI).
