### ISSUE TITLE
Can these codes work on Pytorch v1.1.0?

### ISSUE THREAD

**Issue by SnowyJune973** [Sha-Lab/FEAT#28]
Hi! The codes are really neat! Thanks for sharing!
I notice that it requires a Pytorch>=1.4. However because of the limitation of my working environment,  the CUDA requirement of Pytorch v1.4 can't be realized, so I wonder if the codes will work on lower versions of Pytorch that work with CUDA 9.0 (pytorch v1.1.0 for example)?

**Comment by Han-Jia** [comment]
Yes, the code works with lower versions of PyTorch, but you may need to change some functions to make them compatible (e.g., change flatten() to view(-1) in protonet.py).
