### ISSUE TITLE
How to do inference on single image ?

### ISSUE THREAD

**Issue by samreen98** [Sha-Lab/FEAT#3]
Hi, I want to check result of trained model on single image. It will be really very helpful if you can provide code to directly predict the output class for input query image.

**Comment by Han-Jia** [comment]
Hello,

Few-shot learning aims to build a classifier on a dataset (K-Shot N-Way) with limited images in each class. So the classifier is based on the current N classes, both for embedding based methods (like Matching Network and Prototypical Network) or optimization based methods (like MAML). 

You can use the eval_xx.py script to do inference on a single image given a few-shot training set.

**Comment by samreen98** [comment]
@Han-Jia  ,thanks for your quick response.
I tried eval_feat.py to do inference on single image. But it seems it requires few code changes as image on which I wants to do inference is a random image and not a part of mini imagenet dataset. But it belongs to one of the class of that dataset.

**Comment by Han-Jia** [comment]
Hello, samreen98,

1. Matching Network, Prototypical Network, and FEAT are embedding based few-shot approaches, and learn effective embedding for few-shot learning. Classification with the learned embeddings is based on a nearest neighbor/prototype way, so a (few-shot) training set is necessary for classification. 

2. To evaluate new images, you can try to modify the dataloader (the dataset class).
