### ISSUE TITLE
Where is the testing scripts for FEAT?

### ISSUE THREAD

**Issue by WHQ1111** [Sha-Lab/FEAT#31]
How can I test the model after meta-training?

**Comment by Han-Jia** [comment]
Hi, 

A learned model is evaluated in [train_fsl.py](https://github.com/Sha-Lab/FEAT/blob/9e89693e09f1a19f1b2e8ce9637ded1a0098f33b/train_fsl.py#L20).

A given model could be evaluated by commenting trainer.train() without meta-training.
