### ISSUE TITLE
a question about resnet-18/12  kernel size

### ISSUE THREAD

**Issue by Sword-keeper** [Sha-Lab/FEAT#34]
Hi  that's really a nice code!  However, i have a question about resnet.  In the resnet paper, resnet's first conv layer's kernel size is 7. But  in your code , I found the first conv kernel size is 3. I also found other codes which use resnet-12 or 18. They also set the kernel size is 3.  
     What's more, I read the TADAM's paper which design the resnet-12(maybe not). It just use blocks, didn't add conv layer before the blocks.
    Could you tell me why you change conv kernel size ?  Thank you !

**Comment by Sword-keeper** [comment]
I print your resnet-18's  output size. Could you tell me why you didn't set the 128 channel?
![image](https://user-images.githubusercontent.com/43240918/86365236-d360fe00-bcab-11ea-8613-db850d093e5c.png)

**Comment by Han-Jia** [comment]
We follow the ResNet-12 of [MetaOptNet](https://github.com/kjunelee/MetaOptNet/blob/master/models/ResNet12_embedding.py) and ResNet-18 of [SimpleShot](https://github.com/mileyan/simple_shot/blob/master/src/models/ResNet.py) (results with ResNet-18 are not reported in the paper).

The main reason is that the images used in FSL experiments are small images (84x84), so we should remove some downsampling operations and do not need a large kernel size.
