### ISSUE TITLE
no avg_pooling in resnet-12?

### ISSUE THREAD

**Issue by Tsingularity** [Sha-Lab/FEAT#44]
Hi thanks for the great work!

I read your code very carefully but i am really confused here. In the resnet-12.py file, the forward function is like this:

```
  def forward(self, x):
        x = self.layer1(x)
        x = self.layer2(x)
        x = self.layer3(x)
        x = self.layer4(x)
        if self.keep_avg_pool:
            x = self.avgpool(x)
        x = x.view(x.size(0), -1)
        return x
```

and

```
def Res12(keep_prob=1.0, avg_pool=False, **kwargs):
    """Constructs a ResNet-12 model.
    """
    model = ResNet(BasicBlock, keep_prob=keep_prob, avg_pool=avg_pool, **kwargs)
    return model
```

you can see here the default argument for avg_pool is false. Thus the output feature vector is 5*5*640 dimension instead of 640, which is claimed in your papers.

And in the base fewshot model, i don't see the avg_pool argument is specified as True:

```
class FewShotModel(nn.Module):
    def __init__(self, args):
        super().__init__()
        self.args = args
        if args.backbone_class == 'ConvNet':
            from model.networks.convnet import ConvNet
            self.encoder = ConvNet()
        elif args.backbone_class == 'Res12':
            hdim = 640
            from model.networks.res12 import ResNet
            self.encoder = ResNet()
        elif args.backbone_class == 'Res18':
            hdim = 512
            from model.networks.res18 import ResNet
            self.encoder = ResNet()
        elif args.backbone_class == 'WRN':
            hdim = 640
            from model.networks.WRN28 import Wide_ResNet
            self.encoder = Wide_ResNet(28, 10, 0.5)  # we set the dropout=0.5 directly here, it may achieve better results by tunning the dropout
        else:
            raise ValueError('')
```

The same as other fewshot models.

Could u please explain this here? thanks!

**Comment by Han-Jia** [comment]
Hi,

In the FewShotModel class, we call the [ResNet](https://github.com/Sha-Lab/FEAT/blob/47bdc7c1672e00b027c67469d0291e7502918950/model/networks/res12.py#L73) directly not the Res12 function, where the avg_pool is set to True.

**Comment by Tsingularity** [comment]
thanks for the response! Yeah i also noticed the difference when I actually started working on the code lol. sorry about forgetting to close the issue.
