### ISSUE TITLE
请问可否提供WRN作backbone时fine-tune阶段训练的相关参数

### ISSUE THREAD

**Issue by SnowyJune973** [Sha-Lab/FEAT#49]
实测在使用WRN作backbone时，模型的效果会大幅下降……大概降到77左右（FEAT 5way5shot miniimagenet 有数据增强）。训练相关的参数我都使用了默认值。预训练模型使用的是您README中提供的那个。
十分感谢！

**Comment by Han-Jia** [comment]
抱歉回复较晚。

使用WRN作为Backbone时，一般要使用 --fix_bn选项，将encoder设置为eval()模式，BN不更新、Dropout关闭，此时进行fine-tune会有比较好的效果。
