### ISSUE TITLE
About the 5-shot results on miniimagenet

### ISSUE THREAD

**Issue by zhanyuanyang** [Sha-Lab/FEAT#50]
Hi, thanks for your nice work!

I use training scripts given in README.md with pretrained ResNet12 model:

`python train_fsl.py  --max_epoch 200 --model_class FEAT  --backbone_class Res12 --dataset MiniImageNet --way 5 --eval_way 5 --shot 5 --eval_shot 5 --query 15 --eval_query 15 --balance 0.1 --temperature 64 --temperature2 32 --lr 0.0002 --lr_mul 10 --lr_scheduler step --step_size 40 --gamma 0.5 --gpu 1 --init_weights ./saves/initialization/miniimagenet/Res12-pre.pth --eval_interval 1 --use_euclidean`

But I got "Test acc=0.7821 + 0.0015" which is far lower from the results "82.05%" reported on paper.

![image](https://user-images.githubusercontent.com/23455720/109916888-5cbf4900-7cef-11eb-8058-17c0cbc0ffb5.png)

Did I miss something？

**Comment by Han-Jia** [comment]
Please try with the dataset from [this link](https://drive.google.com/file/d/1BCxmqLANXHbBaWs8A7_jqfVUv8mydp5R/view?usp=sharing) where the model is pre-trained from.

**Comment by zhanyuanyang** [comment]
Thanks for the reply, I try the dataset downloaded from the above link, and I got:

![image](https://user-images.githubusercontent.com/23455720/110737907-4f630b00-8269-11eb-8945-6b91743deeb1.png)

Is there any difference between these two miniimagenet datasets? ( I used the same split method)

**Comment by Han-Jia** [comment]
I use the dataset provided from the paper "optimization as a model for few-shot learning". There may exist some dataset variants with different pre-processing or sizes. 

I think the main reason for the difference is the matching between the dataset and the pre-trained weights. You can try pre-training a model over your dataset and then fine-tune with the meta-learning methods. It may get better results.

**Comment by zhanyuanyang** [comment]
I have understood and thank you very much for your reply.
