### ISSUE TITLE
Could you give the hyperparameters  for the CUB ?

### ISSUE THREAD

**Issue by xue19890510** [Sha-Lab/FEAT#55]
Thank you for your great work.
could you give the hyperparameters  for the CUB ? like the 
python train_fsl.py  --max_epoch 200 --model_class FEAT  --backbone_class Res12 --dataset MiniImageNet --way 5 --eval_way 5 --shot 1 --eval_shot 1 --query 15 --eval_query 15 --balance 0.01 --temperature 64 --temperature2 64 --lr 0.0002 --lr_mul 10 --lr_scheduler step --step_size 40 --gamma 0.5 --gpu 1 --init_weights ./saves/initialization/miniimagenet/Res12-pre.pth --eval_interval 1 --use_euclidean
for the 1 shot and 5 shot, thank you very much!
@Han-Jia

**Comment by Han-Jia** [comment]
Hi,

We use the images from CUB cropped based on the bounding boxes. With the pre-trained ConvNet backbone, we use the following hyper-parameters for both 1-shot and 5-shot cases:
lr = 0.0001, lr_mul = 10, step_size = 20, gamma = 0.5, temperature = 64, temperature2 = 16, balance = 0.1;
