### ISSUE TITLE
请问关于提高准确率的建议

### ISSUE THREAD

**Issue by YiX98** [Sha-Lab/FEAT#57]
感谢你们提供FEAT源码！我尝试用自己的数据集，SEEN(train)有两类，UNSEEN(validate)有4类。 我在SEEN classes上做预训练
`python3 pretrain.py --dataset CustomizedData --lr 0.001 --batch_size 128 --max_epoch 600 --schedule 170 300 400 500 --gamma 0.1 --backbone_class ConvNet`
得到
[dist] val acc = 0.5646
[sim] val acc = 0.5758
然后用此模型做FEAT
`python3 train_fsl.py  --max_epoch 200 --model_class FEAT --use_euclidean --backbone_class ConvNet --dataset CustomizedData --way 2 --eval_way 4 --shot 5 --eval_shot 5 --query 15 --eval_query 15 --balance 0.1 --temperature 32 --temperature2 64 --lr 0.0001 --lr_mul 10 --lr_scheduler step --step_size 20 --gamma 0.5 --gpu 14 --init_weights ./saves/initialization/miniimagenet/con-pre.pth --eval_interval 1`
只能在epoch 7 得到最高acc = 0.6272
请问有什么修改建议可以提高准确率吗？

还有另一个问题，请问如果像我这么正常运行是没有用到test集的吧？

**Comment by Han-Jia** [comment]
你好，

建议从以下方面考虑：
1. pretrain的参数可能要调整，之前的参数是针对MiniImageNet的，针对不同的数据集最优的参数会不同。val acc这里应该是计算4类的分类准确率，57%感觉偏低了；
2. 在meta-training过程中，temperature针对不同的数据集也会有不同，temperature的大小会影响到pretrain权重的作用

如果UNSSEN是meta-val set，则这个过程中没有用到meta-test。

**Comment by YiX98** [comment]
感谢回复，我又重新尝试pretrain这一步了，即使用相同的命令运行也得不到好的结果，还不如第一次运行的0.5646.
这几次运行只能得到0.32左右的acc。请问这个训练能得到好结果的概率是很随机的吗？ pretrain这一步需要调的参数是不是就是learning rate和schedule呢？

还有请问trainfsl的temperature/temperature2各自代表什么呢？

还有请问时什么原因导致trainfsl在前几个epoch达到最高acc，之后acc会降低呢？

**Comment by Han-Jia** [comment]
一般pretrain就是调节learning rate和schedule，同样的参数下最终性能不会变化过大。

temperature/temperature2分别为目标损失和正则中的temperature，对于目标损失和正则中计算logit后会除以temperature进行调节。

由于模型已经有预训练权重，所以可能产生在tranfsl之后accuracy先增加后减少（过拟合）的情况。
