### ISSUE TITLE
Trained models and optimal hyperparameters

### ISSUE THREAD

**Issue by chengyanz** [Sha-Lab/FEAT#6]
Hi, you have done an amazing work! I really like this work. If possible, could you please send me the  well-trained models (protoNet, matchingNet and FEAT) and optimal hyperparameters in training (like temperature)?

**Comment by Han-Jia** [comment]
Hello, the well-trained models of FEAT can be download from the project page. 

I use the following hyper-parameters during training:

- Baselines
- ../../anaconda3/bin/python3.6 train_protonet.py --lr 0.0001 --temperature 32 --max_epoch 200 --model_type ConvNet --dataset MiniImageNet --init_weights ./saves/initialization/miniimagenet/con-pre.pth --shot 1 --way 5 --gpu 0
- ../../anaconda3/bin/python3.6 train_protonet.py --lr 0.0001 --temperature 32 --max_epoch 200 --model_type ConvNet --dataset MiniImageNet --init_weights ./saves/initialization/miniimagenet/con-pre.pth --shot 5 --way 5 --gpu 0
- ../../anaconda3/bin/python3.6 train_matchnet.py --lr 0.0001 --temperature 1 --max_epoch 200 --model_type ConvNet --dataset MiniImageNet --init_weights ./saves/initialization/miniimagenet/con-pre.pth --shot 1 --way 5 --gpu 0
- ../../anaconda3/bin/python3.6 train_matchnet.py --lr 0.0001 --temperature 1 --max_epoch 200 --model_type ConvNet --dataset MiniImageNet --init_weights ./saves/initialization/miniimagenet/con-pre.pth --shot 5 --way 5 --gpu 0
- ../../anaconda3/bin/python3.6 train_matchnet.py --lr 0.0001 --temperature 1 --max_epoch 200 --model_type ConvNet --dataset MiniImageNet --init_weights ./saves/initialization/miniimagenet/con-pre.pth --shot 1 --way 5 --gpu 0--use_bilstm True
- ../../anaconda3/bin/python3.6 train_matchnet.py --lr 0.0001 --temperature 1 --max_epoch 200 --model_type ConvNet --dataset MiniImageNet --init_weights ./saves/initialization/miniimagenet/con-pre.pth --shot 5 --way 5 --gpu 0--use_bilstm True

- FEAT
- ../../anaconda3/bin/python3.6 train_feat.py --lr 0.0001 --temperature 32 --max_epoch 200 --model_type ConvNet --dataset MiniImageNet --init_weights ./saves/initialization/miniimagenet/con-pre.pth --shot 1 --way 5 --gpu 0 --balance 10 --step_size 50 --gamma 0.1 --lr_mul 10
- ../../anaconda3/bin/python3.6 train_feat.py --lr 0.0001 --temperature 16 --max_epoch 200 --model_type ConvNet --dataset MiniImageNet --init_weights ./saves/initialization/miniimagenet/con-pre.pth --shot 5 --way 5 --gpu 0 --balance 10 --step_size 50 --gamma 0.1 --lr_mul 10
- ../../anaconda3/bin/python3.6 train_feat.py --lr 0.0001 --temperature 128 --max_epoch 100 --model_type ResNet --dataset MiniImageNet --init_weights ./saves/initialization/miniimagenet/res-pre.pth --shot 1 --way 5 --gpu 0 --balance 10 --step_size 10 --gamma 0.5 --lr_mul 10
- ../../anaconda3/bin/python3.6 train_feat.py --lr 0.0001 --temperature 128 --max_epoch 100 --model_type ResNet --dataset MiniImageNet --init_weights ./saves/initialization/miniimagenet/res-pre.pth --shot 5 --way 5 --gpu 0 --balance 10 --step_size 20 --gamma 0.5 --lr_mul 10

**Comment by chengyanz** [comment]
Thanks for the much helpful information! Can you kindly provide hyperparameters for baselines when using resnet as well? 
Do you mind releasing the trained baseline models (after running train_protonet and train_matchnet)?

**Comment by Han-Jia** [comment]
Sorry for the late reply. For ProtoNet + ResNet, I use lr = 0.001, T = 64; schedule = 10-0.2, and for MatchingNet, I use lr = 0.001, T = 1; schedule  = 10-0.2. We will release the pre-trained baseline model later.
