### ISSUE TITLE
有关Pre-Avg和Post_Avg

### ISSUE THREAD

**Issue by sherrijj** [Sha-Lab/FEAT#61]
请问，paper里有说Pre-Avg  version比Post-Avg version好，但为什么代码里正则时要用Post_Avg?是因为两种loss计算不一样要这样吗？希望得到你们的指点，谢谢！

**Comment by Han-Jia** [comment]
论文中进行Pre-AVG和Post-AVG主要是针对support set中的样本，这里Pre-AVG能够使得对中心（Prototype）的估计相对准确。

而正则中主要是考虑希望能够对Transformer进行约束，希望通过Transformer进行变换之后的Embedding能够有Contrastive的效果，变换之后的样本离同类中心近，离其他类别远。
