### ISSUE TITLE
关于位置编码positional encoding

### ISSUE THREAD

**Issue by YiX98** [Sha-Lab/FEAT#65]
感谢你们的工作！
我发现文中提到了位置编码，但是每个episode输入的一系列图片好像不像句子中的单词一样有先后位置，而只是来自不同类的个体。所以请问为什么我们还需要位置编码呢？

**Comment by Han-Jia** [comment]
我们在使用Transformer时没有使用位置编码，具体可参见feat.py文件。

文章中探究了Transformer位置的影响，即在计算类别中心之前或之后进行Embedding Adaptation的影响。
