### ISSUE TITLE
Question about lr and gamma.

### ISSUE THREAD

**Issue by zhanyuanyang** [Sha-Lab/FEAT#67]
Should I use the same lr and gamma for both 1-shot and 5-shot tasks?

**Comment by Han-Jia** [comment]
Yes, using the same lr and gamma for 1/5-shot tasks can get competitive results. 

But with carefully tuned lr and gamma (especially gamma and stepsize) can get further improvement.

**Comment by zhanyuanyang** [comment]
Thank you for your reply.


> Yes, using the same lr and gamma for 1/5-shot tasks can get competitive results.

Is this setting mandatory? 

Or is it possible to use different lr for 1-shot and 5-shot tasks respectively?

**Comment by Han-Jia** [comment]
It is not mandatory. We can use different learning rates for 1-shot and 5-shot tasks.

**Comment by zhanyuanyang** [comment]
I got it, thank you very much!
