### ISSUE TITLE
Download the pretrained weights

### ISSUE THREAD

**Issue by OverVan** [Sha-Lab/FEAT#70]
Hello, I could not have access to google drive because of regional restrictions.
Can I get all the pretrained weights by other approaches?
Thank you!

**Comment by Han-Jia** [comment]
Hi, 

please download the [initialization weights](https://lamdanjueducn-my.sharepoint.com/:u:/g/personal/yehj_lamda_nju_edu_cn/EYePH8kytT1Evc1KNa3BxMsB23owsKfQqUA2a78YQYPSgw?e=edn8XW) and [learned model](https://lamdanjueducn-my.sharepoint.com/:u:/g/personal/yehj_lamda_nju_edu_cn/EaKITYb9vyVJqvvRun0j9u8BjPHDVAR9AHCiNULO1gDwag?e=V9AgOW) from OneDrive.
