### ISSUE TITLE
Question about proto

### ISSUE THREAD

**Issue by LoveMiki** [Sha-Lab/FEAT#71]
Hi

I noticed that in line 99: proto = support.mean(dim=1)  of feat.py file, you calculate the mean of the first dimension. However, I think the shape of support is (batch_size, way, shot, d). Shouldn't it be averaged over the second dimension?

Thank you

**Comment by Han-Jia** [comment]
Hi, the first dimension is dim = 0.

For dim = 1, we average the shot dimension since the shape of the support is (batch size, shot, way, channel)
