### ISSUE TITLE
the pre-training hyperparameters for ResNet12  on CUB

### ISSUE THREAD

**Issue by DongYY127** [Sha-Lab/FEAT#74]
My problem is the same as #69，
In the experiment, I found that the pre-training strategy had a significant effect on the final experimental results，
And I want to recreate ResNet12 pre-trained weights for CUB. 
Could you please give some suggestions for the hyperparameters that pretraining ResNet12 on CUB?

like the pretrain ResNet12 on MiniImageNet "python pretrain.py --batch_size 128 --max_epoch 500 --lr 0.1 --dataset MiniImageNet --backbone_class Res12 --schedule 350 400 440 460 480 --gamma 0.1"

**Comment by Han-Jia** [comment]
Sorry for the late reply. 

For CUB, please try lr = 0.1, epoch = 600, schedule = 400, 500, 550, 580, gamma=0.1
