### ISSUE TITLE
Pretraining hyperparameters for CUB dataset

### ISSUE THREAD

**Issue by mayug** [Sha-Lab/FEAT#76]
Hi, 

Could you please provide the hyperparameters used for pertaining convnet and res12 on the CUB dataset?

Also, what were the best val_dist acc and val_sim acc you got for convnet and res12 on the CUB dataset in the pertaining stage?

Thanks and Regards
Mayug

**Comment by Han-Jia** [comment]
Hi,

For ConvNet, please try 
python pretrain.py --lr 0.001 --batch_size 256 --max_epoch 500 --backbone_class ConvNet --schedule 300 350 400 450 --gamma 0.1 --dataset CUB --query 15
[Dist] best epoch 141, current best val acc=0.1758 (over all meta-val classes)
[Sim] best epoch 121, current best val acc=0.1942

For ResNet, please use
lr = 0.1, epoch = 600, schedule = 400, 500, 550, 580, gamma=0.1
we only record the 1-shot 5-way results based on learned embedding with the cosine classifier, it achieves almost 73%.
