### ISSUE TITLE
Can you upload data/tieredimagenet/split please?

### ISSUE THREAD

**Issue by CandiceHan123** [Sha-Lab/FEAT#78]
hello，
I would like to ask how to devide tierdimagenet? If it's convenient for you, can you upload the split folder of tieredimagenet?
best wishes.

**Comment by Han-Jia** [comment]
Hello, 

TieredImageNet could be found at [this link](https://drive.google.com/file/d/1nVGCTd9ttULRXFezh4xILQ9lUkg0WZCG/view) from the repo of MetaOptNet. It is directly partitioned into meta-train/val/test sets. 

[This repo](https://github.com/yaoyao-liu/tiered-imagenet-tools) also provides more details about the split of the dataset.
