### ISSUE TITLE
source of the miniimagenet dataset

### ISSUE THREAD

**Issue by icoz69** [Sha-Lab/FEAT#8]
hi, very nice work.
where could I download the MiniImageNet dataset ? or should I download the whole imagenet instead?

**Comment by Han-Jia** [comment]
Hi, 

We use the [split](https://github.com/twitter/meta-learning-lstm/tree/master/data/miniImagenet) and images reorganized by [Sachin Ravi](http://www.cs.princeton.edu/~sachinr/), please email him to obtain the link of the dataset.

This [repo](https://github.com/renmengye/few-shot-ssl-public) also provides the pickle form of the dataset.

**Comment by icoz69** [comment]
> Hi,
> 
> We use the split and images reorganized by [Sachin Ravi](sachinr@princeton.edu), please email him to obtain the link of the dataset.
> 
> This [repo](https://github.com/renmengye/few-shot-ssl-public) also provides the pickle form of the dataset.

Thanks a lot
